version: '1'

services:

  redis:
    image: redis:latest
    hostname: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_app_copy.sh
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    links:
      - redis


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery_copy.sh
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
